name: Build GameVault app

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Build backend API (.NET)
    runs-on: ubuntu-latest
    env:
      MY_PATH: Backend/GameVaultApi/GameVaultApi.sln

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore $MY_PATH

      - name: Build Backend
        run: dotnet build $MY_PATH --no-restore --configuration Release

      - name: Count lines of code in Backend
        run: |
          sudo apt-get update && sudo apt-get install -y cloc
          cloc Backend/GameVaultApi

      - name: Simulate Deployment (Backend)
        run: echo "Simulated deployment of backend complete!"

  frontend:
    name: Build Frontend (.NET)
    runs-on: ubuntu-latest
    env:
      MY_PATH: Frontend/GameVaultApp.sln

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore $MY_PATH

      - name: Build Frontend
        run: dotnet build $MY_PATH --no-restore --configuration Release

      - name: Count lines of code in Frontend
        run: |
          sudo apt-get update && sudo apt-get install -y cloc
          cloc Frontend

      - name: Simulate Deployment (Frontend)
        run: echo "Simulated deployment of frontend complete!"
